### ISSUE TITLE
URGENT: Update organisation types

### ISSUE THREAD

**Issue by bradydan** [consilience/Xero-OpenAPI#1]

**Comment by bradydan** [comment]
Jason:

> [Xero's version of this repo is] deprecated - Xero are no longer maintaining it, so we are on our own keeping up with the API with our fork.
>
> They are just doing their OAuth 2.0 branch now.
> 
> But they didn't make a clean cut - it just kind of faded from one to the other with no tags at the point of change

When we switch to OAuth 2.0 we can use that OAuth 2.0 branch

Jason: 

> [We need] a set of automated tests that can watch releases on the Xero git repo and pull in the latest, build everything, run the tests that exercise everything we do with Xero, and notify us.
> 
> And keeping up with incremental changes will ensure we deal with little issues as they arrive.

**Comment by judgej** [comment]
Public fork of a public repo.
